### ISSUE TITLE
NULL response getting passed around

### ISSUE THREAD

**Issue by jameslamb** [nealrichardson/httptest#16]
Hello! Thank you for this excellent package. I use it all the time.

I encountered a strange error today. Doing this:

```{r}
start_capturing()
httr::GET("dafasdfasdflkm;aslkdfmasdf.com")
```

Returned:

```{r}
 Error in if (method != "GET") { : argument is of length zero 
```

Based on the docs, I would have expected `httptest` to write out a `.R` file mocking the failed request. I spent about half an hour trying to walk my way back through the code interactively tonight, but I couldn't track it down.

Hope you are able to reproduce it!

**Comment by jameslamb** [comment]
Thanks for the prompt reply @nealrichardson !

That all makes sense to me. Can you point to some documentation on how to set up that `.R` mock file? I haven't found an example of it in your vignettes or roxygen stuff. I was using `capture_requests` because I wanted to try to mock out some 4xx and 5xx responses.

Mainly I'm wondering how to figure out what the expected file path is. I've been able to do this with 2xx stuff without issue (thanks again for making it so user-friendly!) but not sure where to start on non-successful requests.

Cheers,

-James

**Comment by nealrichardson** [comment]
With `httr`, 4xx or 5xx responses don't error like that. They return a `response` object that has a `status_code` of 400 or whatever. To get a feel for how `httr` does this, or even to set up your tests, try making requests at httpbin.org: you can get any response status you want from them, e.g. http://httpbin.org/status/418 returns 418 status. You could record that and then rename it to whatever path you need it to be for your tests.

For httptest, the expected file path is whatever it would be for a successful response--the response status doesn't affect the file path (other than perhaps the extension because error responses (currently) are always written as verbose `.R` files), only the contents of the file. 

The best reference I have for how to test >400 status responses is probably https://enpiar.com/2017/06/21/7-hard-testing-problems-made-easy-by-httptest/, which links to some real examples as well.
