### ISSUE TITLE
Bad redacting when URL parameters are URL themselves

### ISSUE THREAD

**Issue by ramiromagno** [nealrichardson/httptest#22]
Example:

The URL:

```
https://www.ebi.ac.uk/gwas/rest/api/studies/search/findByEfoUri?uri=http://www.ebi.ac.uk/efo/EFO_0004761&page=0&size=20
```

Gets written as:

```
<pkg_path>/tests/testthat/www.ebi.ac.uk/efo/EFO_0004761&page=0&size=20.json
```

If I use instead:

```
https://www.ebi.ac.uk/gwas/rest/api/studies/search/findByEfoUri?uri=http:%2f%2fwww.ebi.ac.uk%2fefo%2fEFO_0004761
```

Then I get the expected mock file:

```
<pkg_path>/tests/testthat/www.ebi.ac.uk/gwas/rest/api/studies/search/findByEfoUri-5bb3d9.json
```

**Comment by nealrichardson** [comment]
Hard for me to say with certainty what's going on without seeing the code you ran to generate this, but it is expected behavior that all occurrences of the regular expression pattern are replaced, not just the first one--that's what `gsub()` does. And `gsub_request/response()` do not currently un-escape URL-encoded strings (though one might want it to), so it's not surprising that if `/` is encoded to `%2F` that the regular expression won't match it.

**Comment by ramiromagno** [comment]
OK, thank you!
