### ISSUE TITLE
404 in pkgdown website

### ISSUE THREAD

**Issue by maelle** [nealrichardson/httptest#39]
https://enpiar.com/r/httptest/reference/with_mock_api.html

**Comment by maelle** [comment]
(sorry for the succinct issue, I want to keep reading :-D )

**Comment by nealrichardson** [comment]
Thanks. Apparently this is what you get for building the website on a case-insensitive file system. See https://enpiar.com/r/httptest/reference/with_mock_API.html. Will get the URL fixed in the next release.

**Comment by maelle** [comment]
I wonder whether that's also something that should be tweaked in roxygen2/pkgdown?

**Comment by nealrichardson** [comment]
I don't think they can; the problem is outside R. The issue was that the function was originally `with_mock_API` but then I standardized the naming conventions to follow `httr` and renamed the function to all lower. So when I updated the pkgdown site, my macOS file system didn't recognize the difference in file names between API and api so git wasn't able to register the change.

**Comment by nealrichardson** [comment]
This should be fixed now. Thanks for reporting!
